### ISSUE TITLE
Возникают ошибки при сборке.

### ISSUE THREAD

**Issue by serg3295** [fikin/nodemcu-device#29]
Здравствуйте, Николай.
Я попробовал вашу сборку для nodemcu. Очень много нового для себя узнал. Спасибо.

Есть небольшое замечание. При первоначальной установке minify установился как root:root, соответственно в процессе сборки получил permission denied. Поменял владельца на пользователя, сборка пошла.

И вопросы.
1. Выдаёт в самом конце сборки вот такие ошибки
```
./vendor/nodemcu-firmware/tools/spiffsimg/spiffsimg -f ./vendor/nodemcu-firmware/bin/0x%x-0x100000.img -c 0x100000 -U 0x100000 -r ./vendor/spiffs.lst -d
make[2]: Leaving directory '/home/serg/Projects/lua/nodemcu/nodemcu-device'
make[1]: Leaving directory '/home/serg/Projects/lua/nodemcu/nodemcu-device'
make -f Makefile-spiffs.mk X_BRANCH_NATURE=esp8266 spiffs-image
make[1]: Entering directory '/home/serg/Projects/lua/nodemcu/nodemcu-device'
ls: cannot access '*.lua': No such file or directory
ls: cannot access '*.lua': No such file or directory
ls: cannot access '*.lc': No such file or directory
/home/serg/Projects/lua/nodemcu/nodemcu-device/./vendor/nodemcu-firmware/luac.cross: cannot open *.lc: No such file or directory
make[1]: *** [Makefile-spiffs.mk:66: lfs-image] Error 1
make[1]: Leaving directory '/home/serg/Projects/lua/nodemcu/nodemcu-device'
make: *** [Makefile:124: spiffs-image] Error 2
```
Однако, всё собирается и прошивка работает.

2.  Для esp32 ещё не пробовал, поэтому вопрос - оно сейчас работает? Что нужно в конфиге писать, чтобы собрать ветку dev-esp32?

**Comment by fikin** [comment]
sorry, мои руский очен плохии. увидиш, я с болгарии.

your make-related observations are correct, i simply underplayed their need to fix. if you want, you're welcomed to send me pull request with improvements.

about esp32 branch, building used to work fine some half / one year ago. haven't tries lately. 
you have to change the "branch" variable and select lua modules you want in build.config.

and here lies the real problem with esp32 - compared to 8266 the (not) available nodemcu firmware libraries and wherever present differences in signatures. 
coding fully reusable modules becomes complicated if not plain impossible.
and i somewhat reverted back my focus to 8266 only, for now.

for esp32, i'd likely create separate repo and accept that common code would be duplicated manually.
to some extend that should have happened with firmware too, as there are plenty of c-level differences which do not make much sense to keep in a branch. but that in itself is a closed story ...

**Comment by fikin** [comment]
ok, have fun. reopen if needed.
